library(virtualspecies)
library(rnaturalearth)
library(tidyverse)
library(fuzzySim)
library(mgcv)
library(ranger)
library(PresenceAbsence)
library(tidyr)
library(dplyr)
library(ggplot2)
library(gghalves)
library(biomod2)
library(readr)
library(vegan)
library(FSA)

temp<-raster("wc2.1_10m_bio_1.tif")
preci<- raster("wc2.1_10m_bio_12.tif")
elev<- raster("wc2.1_10m_elev.tif")
Asia<- ne_countries(scale="medium", type="map_units", returnclass="sf", country=c('Myanmar','Thailand','Laos','Cambodia','Vietnam'))
study_area<- select(Asia, geometry, name_long)
elev<- mask(elev,study_area)
temp<- mask(temp,study_area)
preci<- mask(preci,study_area)

envi_stack<-stack(elev, temp, preci)
names(envi_stack)<- c("elev", "temp", "preci")
ex<- extent(90, 112, 4, 30)
envi<- crop(envi_stack, ex)
names(envi)<- c("elev", "temp", "preci")
plot(envi)

